---
- hosts: all
  gather_facts: false

  roles:
    - role: rhel_system_roles.crypto_policies
    - role: rhel_system_roles.network
    #- role: redhat.rhel_system_roles.crypto_policies
    #- role: redhat.rhel_system_roles.network
